// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcquisitionSettingsUpdate = { minimum_score: number | null, auto_acquire_score: number | null, preferred_language: string | null, blocked_terms: Array<string> | null, };
