// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudiobookshelfIntegrationRecord = { enabled: boolean, base_url: string, library_id: string, has_api_key: boolean, mark_existing_during_search: boolean, };
