// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthUserRecord } from "./AuthUserRecord";

export type AuthBootstrapStatus = { setup_required: boolean, authenticated_user: AuthUserRecord | null, };
