// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestationPreference } from "./ManifestationPreference";
import type { MediaType } from "./MediaType";
import type { SubmissionIntakeMode } from "./SubmissionIntakeMode";

export type CreateSubmissionRequest = { intake_mode: SubmissionIntakeMode | null, selected_work_id: string | null, title: string | null, author: string | null, notes: string | null, media_types: Array<MediaType>, preferred_language: string | null, manifestation: ManifestationPreference, allow_duplicate: boolean, };
