// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestationPreference } from "./ManifestationPreference";
import type { MediaType } from "./MediaType";

export type CreateRequestSelection = { selected_work_id: string | null, media_types: Array<MediaType>, preferred_language: string | null, manifestation: ManifestationPreference, };
