// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QbittorrentSettingsUpdate } from "./QbittorrentSettingsUpdate";

export type DownloadClientSettingsUpdate = { qbittorrent: QbittorrentSettingsUpdate | null, };
