// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudiobookLayoutPreset } from "./AudiobookLayoutPreset";
import type { EbookImportMode } from "./EbookImportMode";

export type ImportSettingsRecord = { ebook_import_mode: EbookImportMode, ebook_passthrough_root: string | null, ebook_naming_template: string, audiobook_layout_preset: AudiobookLayoutPreset, calibre_command: string, };
