// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryScanJobRecord = { id: bigint, started_at: string, completed_at: string | null, ebooks_found: bigint, audiobooks_found: bigint, duplicates_skipped: bigint, error_message: string | null, };
