// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManifestationPreference = { edition_title: string | null, preferred_narrator: string | null, preferred_publisher: string | null, graphic_audio: boolean, };
