// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataSettingsUpdate = { base_url: string | null, cover_base_url: string | null, };
