// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationTargetKind } from "./NotificationTargetKind";

export type NotificationSettingsRecord = { enabled: boolean, target_kind: NotificationTargetKind, target_url: string, has_auth_token: boolean, auth_header: string | null, };
