// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProwlarrIntegrationUpdate = { enabled: boolean | null, sync_enabled: boolean | null, base_url: string | null, api_key: string | null, selected_indexer_ids: Array<number> | null, clear_api_key: boolean, };
