// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QbittorrentSettingsRecord = { enabled: boolean, base_url: string, username: string, category_ebook: string, category_audiobook: string, has_password: boolean, };
