// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestationPreference } from "./ManifestationPreference";
import type { MediaType } from "./MediaType";

export type RequestRecord = { id: string, external_work_id: string, title: string, author: string, media_type: MediaType, preferred_language: string | null, manifestation: ManifestationPreference, state: string, created_at: string, };
