// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestEventKind = "Created" | "SearchCompleted" | "ReviewQueued" | "ReviewApproved" | "ReviewRejected" | "DownloadQueued" | "DownloadCompleted" | "ImportSucceeded" | "SyncSucceeded" | "LibraryDiscovered";
