// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestEventRecord } from "./RequestEventRecord";
import type { RequestRecord } from "./RequestRecord";

export type RequestDetailRecord = { request: RequestRecord, events: Array<RequestEventRecord>, };
