// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestationPreference } from "./ManifestationPreference";
import type { MediaType } from "./MediaType";
import type { RequestListRecord } from "./RequestListRecord";
import type { SubmissionIntakeMode } from "./SubmissionIntakeMode";
import type { SubmissionStatus } from "./SubmissionStatus";

export type RequestSubmissionRecord = { id: string, requested_by_user_id: string, requested_by_username: string, intake_mode: SubmissionIntakeMode, title: string, author: string, external_work_id: string | null, notes: string | null, media_types: Array<MediaType>, preferred_language: string | null, manifestation: ManifestationPreference, status: SubmissionStatus, requires_admin_approval: boolean, allow_duplicate: boolean, linked_requests: Array<RequestListRecord>, created_at: string, updated_at: string, };
