// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestEventKind } from "./RequestEventKind";

export type RequestEventRecord = { id: bigint, request_id: string, kind: RequestEventKind, payload_json: string, created_at: string, };
