// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseCandidate } from "./ReleaseCandidate";

export type ReviewQueueEntry = { id: bigint, request_id: string, candidate: ReleaseCandidate, score: number, explanation: Array<string>, created_at: string, };
