// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcquisitionSettingsRecord } from "./AcquisitionSettingsRecord";
import type { DownloadClientSettingsRecord } from "./DownloadClientSettingsRecord";
import type { ImportSettingsRecord } from "./ImportSettingsRecord";
import type { IntegrationSettingsRecord } from "./IntegrationSettingsRecord";
import type { MetadataSettingsRecord } from "./MetadataSettingsRecord";
import type { StorageSettingsRecord } from "./StorageSettingsRecord";

export type RuntimeSettingsRecord = { storage: StorageSettingsRecord, metadata: MetadataSettingsRecord, download_clients: DownloadClientSettingsRecord, integrations: IntegrationSettingsRecord, import: ImportSettingsRecord, acquisition: AcquisitionSettingsRecord, };
