// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmissionEventRecord = { id: bigint, submission_id: string, kind: string, payload_json: string, created_at: string, };
