// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncedIndexerRecord = { id: bigint, prowlarr_indexer_id: bigint | null, name: string, enabled: boolean, implementation: string, protocol: string | null, base_url: string | null, categories: Array<bigint>, last_synced_at: string, };
