// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export type UpdateUserRequest = { role: UserRole | null, disabled: boolean | null, password: string | null, };
