// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkRecord = { external_id: string, title: string, primary_author: string, first_publish_year: number | null, description: string | null, cover_id: bigint | null, subjects: Array<string>, edition_count: number | null, };
