// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcquisitionSettingsRecord = { minimum_score: number, auto_acquire_score: number, preferred_language: string | null, blocked_terms: Array<string>, };
