// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateSource } from "./DuplicateSource";

export type DuplicateHint = { source: DuplicateSource, label: string, detail: string | null, };
