// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudiobookshelfIntegrationUpdate } from "./AudiobookshelfIntegrationUpdate";
import type { ProwlarrIntegrationUpdate } from "./ProwlarrIntegrationUpdate";

export type IntegrationSettingsUpdate = { prowlarr: ProwlarrIntegrationUpdate | null, audiobookshelf: AudiobookshelfIntegrationUpdate | null, };
