// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudiobookshelfIntegrationRecord } from "./AudiobookshelfIntegrationRecord";
import type { ProwlarrIntegrationRecord } from "./ProwlarrIntegrationRecord";

export type IntegrationSettingsRecord = { prowlarr: ProwlarrIntegrationRecord, audiobookshelf: AudiobookshelfIntegrationRecord, };
