// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationTargetKind } from "./NotificationTargetKind";

export type NotificationSettingsUpdate = { enabled: boolean | null, target_kind: NotificationTargetKind | null, target_url: string | null, auth_token: string | null, auth_header: string | null, clear_auth_token: boolean, };
