// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProwlarrIntegrationRecord = { enabled: boolean, sync_enabled: boolean, base_url: string, has_api_key: boolean, };
