// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QbittorrentSettingsUpdate = { enabled: boolean | null, base_url: string | null, username: string | null, password: string | null, clear_password: boolean, category_ebook: string | null, category_audiobook: string | null, };
