// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaType } from "./MediaType";

export type RequestListRecord = { id: string, title: string, author: string, media_type: MediaType, state: string, created_at: string, };
