// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestSubmissionRecord } from "./RequestSubmissionRecord";
import type { SubmissionEventRecord } from "./SubmissionEventRecord";

export type RequestSubmissionDetailRecord = { submission: RequestSubmissionRecord, events: Array<SubmissionEventRecord>, };
