// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcquisitionSettingsUpdate } from "./AcquisitionSettingsUpdate";
import type { DownloadClientSettingsUpdate } from "./DownloadClientSettingsUpdate";
import type { ImportSettingsUpdate } from "./ImportSettingsUpdate";
import type { IntegrationSettingsUpdate } from "./IntegrationSettingsUpdate";
import type { MetadataSettingsUpdate } from "./MetadataSettingsUpdate";
import type { NotificationSettingsUpdate } from "./NotificationSettingsUpdate";
import type { StorageSettingsUpdate } from "./StorageSettingsUpdate";

export type RuntimeSettingsUpdate = { storage: StorageSettingsUpdate | null, metadata: MetadataSettingsUpdate | null, download_clients: DownloadClientSettingsUpdate | null, integrations: IntegrationSettingsUpdate | null, import: ImportSettingsUpdate | null, acquisition: AcquisitionSettingsUpdate | null, notifications: NotificationSettingsUpdate | null, };
