// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateHint } from "./DuplicateHint";
import type { WorkRecord } from "./WorkRecord";

export type SubmissionSearchCandidate = { work: WorkRecord, duplicate_hints: Array<DuplicateHint>, };
